# Generated by Django 3.1.5 on 2021-01-14 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210114_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('anons', models.CharField(max_length=50, verbose_name='анонс')),
                ('full_text', models.TextField(verbose_name='Текст')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.RemoveField(
            model_name='classname',
            name='anons',
        ),
        migrations.RemoveField(
            model_name='classname',
            name='date',
        ),
        migrations.RemoveField(
            model_name='classname',
            name='full_text',
        ),
        migrations.RemoveField(
            model_name='classname',
            name='id',
        ),
        migrations.RemoveField(
            model_name='classname',
            name='title',
        ),
        migrations.AddField(
            model_name='classname',
            name='test_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.test'),
            preserve_default=False,
        ),
    ]
