# Generated by Django 3.1.5 on 2021-01-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210114_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qwe',
            field=models.ManyToManyField(to='main.test'),
        ),
    ]
