# Generated by Django 3.1.5 on 2021-01-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customuser_qwe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='qwe',
        ),
        migrations.AddField(
            model_name='customuser',
            name='qwe',
            field=models.CharField(default=0, max_length=20, verbose_name='test'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ClassName',
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
