# Generated by Django 3.1.5 on 2021-01-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='q1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='q2',
            field=models.BooleanField(default=False),
        ),
    ]
