# Generated by Django 3.1.5 on 2021-01-15 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210115_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='q2',
        ),
    ]
