# Generated by Django 3.1.5 on 2021-01-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210115_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='temp',
            field=models.BooleanField(default=False),
        ),
    ]
