# Generated by Django 3.1.5 on 2021-01-15 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customuser_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='qwe',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='temp',
        ),
        migrations.CreateModel(
            name='qqq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('les', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lessons')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'les')},
            },
        ),
    ]
