# Generated by Django 3.1.5 on 2021-01-15 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210115_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='quest_user',
            fields=[
                ('quests_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.quests')),
                ('who', models.CharField(blank=True, max_length=50, null=True, verbose_name='Кто выполнил')),
            ],
            bases=('main.quests',),
        ),
        migrations.RemoveField(
            model_name='eeg',
            name='commoninfo_ptr',
        ),
        migrations.RemoveField(
            model_name='property',
            name='EEG',
        ),
        migrations.RemoveField(
            model_name='property',
            name='propertytype',
        ),
        migrations.DeleteModel(
            name='CommonInfo',
        ),
        migrations.DeleteModel(
            name='EEG',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='Propertytype',
        ),
    ]
