# Generated by Django 3.1.5 on 2021-01-16 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='NIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('les_eng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nis_les_eng', to='main.lessons')),
                ('les_kaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nis_les_kaz', to='main.lessons')),
                ('les_mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nis_les_mat', to='main.lessons')),
                ('les_rus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nis_les_rus', to='main.lessons')),
            ],
        ),
        migrations.CreateModel(
            name='KTL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('les_eng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ktl_les_eng', to='main.lessons')),
                ('les_kaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ktl_les_kaz', to='main.lessons')),
                ('les_mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ktl_les_mat', to='main.lessons')),
                ('les_rus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ktl_les_rus', to='main.lessons')),
            ],
        ),
        migrations.CreateModel(
            name='c_direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_KTL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ktl')),
                ('dir_NIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nis')),
            ],
        ),
        migrations.CreateModel(
            name='c_classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(verbose_name='Класс')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.c_direction')),
            ],
        ),
    ]
