# Generated by Django 3.1.5 on 2021-01-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_c_classes_c_direction_ktl_nis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='new_quest',
        ),
        migrations.AddField(
            model_name='c_direction',
            name='class_tag',
            field=models.CharField(default=0, max_length=20, verbose_name='Класс'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='quest_user',
        ),
        migrations.DeleteModel(
            name='quests',
        ),
    ]
