# Generated by Django 3.1.5 on 2021-01-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210116_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktl',
            name='class_tag',
            field=models.CharField(default=0, max_length=20, verbose_name='Класс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nis',
            name='class_tag',
            field=models.CharField(default=0, max_length=20, verbose_name='Класс'),
            preserve_default=False,
        ),
    ]
