# Generated by Django 3.1.5 on 2021-01-17 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210116_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('anons', models.CharField(max_length=50, verbose_name='Краткое описание')),
                ('video', models.CharField(max_length=50, verbose_name='Видео')),
                ('pdf', models.CharField(max_length=50, verbose_name='PDF')),
                ('quest', models.TextField(verbose_name='Текст задачи')),
                ('klass', models.IntegerField(verbose_name='Класс')),
                ('direction', models.CharField(max_length=50, verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.RenameModel(
            old_name='KTL',
            new_name='c_KTL',
        ),
        migrations.RenameModel(
            old_name='NIS',
            new_name='c_NIS',
        ),
        migrations.RemoveField(
            model_name='c_classes',
            name='direction',
        ),
        migrations.AddField(
            model_name='c_classes',
            name='KTL',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.c_ktl'),
        ),
        migrations.AddField(
            model_name='c_classes',
            name='NIS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.c_nis'),
        ),
    ]
