# Generated by Django 3.1.5 on 2021-01-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210118_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='direction',
            field=models.CharField(blank=True, choices=[('nis', 'НИШ'), ('ktl', 'КТЛ'), ('165', '165 Лицей'), ('rfm', 'РФМШ')], default=None, max_length=3, verbose_name='Направление'),
        ),
    ]
