# Generated by Django 3.1.5 on 2021-01-18 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210118_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='c_direction',
            name='dir_KTL',
        ),
        migrations.RemoveField(
            model_name='c_direction',
            name='dir_NIS',
        ),
        migrations.RemoveField(
            model_name='c_ktl',
            name='les_eng',
        ),
        migrations.RemoveField(
            model_name='c_ktl',
            name='les_kaz',
        ),
        migrations.RemoveField(
            model_name='c_ktl',
            name='les_mat',
        ),
        migrations.RemoveField(
            model_name='c_ktl',
            name='les_rus',
        ),
        migrations.RemoveField(
            model_name='c_nis',
            name='les_eng',
        ),
        migrations.RemoveField(
            model_name='c_nis',
            name='les_kaz',
        ),
        migrations.RemoveField(
            model_name='c_nis',
            name='les_mat',
        ),
        migrations.RemoveField(
            model_name='c_nis',
            name='les_rus',
        ),
        migrations.AlterField(
            model_name='course',
            name='direction',
            field=models.CharField(choices=[('nis', 'НИШ'), ('ktl', 'КТЛ'), ('165', '165 Лицей'), ('rfm', 'РФМШ')], max_length=3, verbose_name='Направление'),
        ),
        migrations.DeleteModel(
            name='c_classes',
        ),
        migrations.DeleteModel(
            name='c_direction',
        ),
        migrations.DeleteModel(
            name='c_KTL',
        ),
        migrations.DeleteModel(
            name='c_NIS',
        ),
        migrations.DeleteModel(
            name='lessons',
        ),
        migrations.AddField(
            model_name='purchased',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AddField(
            model_name='purchased',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
