# Generated by Django 3.1.5 on 2021-01-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_time',
            field=models.BooleanField(default=True),
        ),
    ]
