# Generated by Django 3.1.5 on 2021-01-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_customuser_first_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, choices=[('rus', 'Русский'), ('kaz', 'Казахский'), ('eng', 'Английский'), ('mat', 'Математика')], max_length=3, verbose_name='Предмет'),
        ),
    ]
