# Generated by Django 3.1.5 on 2021-01-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210121_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='direction_kz',
        ),
        migrations.RemoveField(
            model_name='course',
            name='direction_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject_kz',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject_ru',
        ),
    ]
