# Generated by Django 3.1.5 on 2021-01-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210121_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='anons_kz',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name_kz',
        ),
        migrations.RemoveField(
            model_name='course',
            name='quest_kz',
        ),
        migrations.AddField(
            model_name='course',
            name='anons_kk',
            field=models.CharField(help_text='Краткое описание', max_length=50, null=True, verbose_name='anons'),
        ),
        migrations.AddField(
            model_name='course',
            name='name_kk',
            field=models.CharField(help_text='Название', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='course',
            name='quest_kk',
            field=models.TextField(help_text='Текст задачи', null=True, verbose_name='quest'),
        ),
        migrations.AlterField(
            model_name='course',
            name='anons',
            field=models.CharField(help_text='Краткое описание', max_length=50, verbose_name='anons'),
        ),
        migrations.AlterField(
            model_name='course',
            name='anons_ru',
            field=models.CharField(help_text='Краткое описание', max_length=50, null=True, verbose_name='anons'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Название', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name_ru',
            field=models.CharField(help_text='Название', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='quest',
            field=models.TextField(help_text='Текст задачи', verbose_name='quest'),
        ),
        migrations.AlterField(
            model_name='course',
            name='quest_ru',
            field=models.TextField(help_text='Текст задачи', null=True, verbose_name='quest'),
        ),
    ]
