# Generated by Django 3.1.5 on 2021-01-30 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_course_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='content',
        ),
    ]
