# Generated by Django 3.1.5 on 2021-02-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20210204_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='var1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Вариант 1'),
        ),
        migrations.AddField(
            model_name='quest',
            name='var2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Вариант 2'),
        ),
        migrations.AddField(
            model_name='quest',
            name='var3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Вариант 3'),
        ),
    ]
