# Generated by Django 3.1.5 on 2021-02-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20210204_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='right_answer',
        ),
        migrations.DeleteModel(
            name='QandA',
        ),
    ]
