# Generated by Django 3.1.5 on 2021-02-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210205_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
