# Generated by Django 3.1.5 on 2021-02-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='right',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='start',
            field=models.BooleanField(default=False),
        ),
    ]
