# Generated by Django 3.1.5 on 2021-02-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20210206_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='correct',
            field=models.CharField(blank=True, choices=[('var1', 'Вариант 1'), ('var2', 'Вариант 2'), ('var3', 'Вариант 3')], max_length=4, verbose_name='Правильный ответ'),
        ),
    ]
