# Generated by Django 3.1.5 on 2021-02-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_quest_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='text',
            field=models.TextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='var1',
            field=models.TextField(blank=True, null=True, verbose_name='Вариант 1'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='var2',
            field=models.TextField(blank=True, null=True, verbose_name='Вариант 2'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='var3',
            field=models.TextField(blank=True, null=True, verbose_name='Вариант 3'),
        ),
    ]
