# Generated by Django 3.1.5 on 2021-03-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20210225_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lvl',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
