# Generated by Django 3.1.5 on 2021-03-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_purchased_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('course_id', models.IntegerField(default=0)),
                ('option_one', models.CharField(max_length=255, verbose_name='Вариант 1')),
                ('option_two', models.CharField(max_length=255, verbose_name='Вариант 2')),
                ('option_three', models.CharField(max_length=255, verbose_name='Вариант 3')),
                ('option_four', models.CharField(max_length=255, verbose_name='Вариант 4')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ')),
            ],
        ),
    ]
